import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  RegisterLink,
  LoginLink,
} from "@kinde-oss/kinde-auth-nextjs/components";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { LogoutLink } from "@kinde-oss/kinde-auth-nextjs/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "First Task | Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="shadow-lg py-3">
          <div className="w-11/12 mx-auto flex justify-between">
            <div>
              <ul className="flex gap-6 justify-center">
                <li>
                  <Link href="/" className="hover:text-blue-700">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/dashboard" className="hover:text-blue-700">
                    Profile
                  </Link>
                </li>
              </ul>
            </div>
            <div className="text-end flex space-x-3">
              {user && user?.email ? (
                <>
                  <button className="px-3 py-1 bg-gray-800 hover:bg-blue-700 text-white rounded-md">
                    <LogoutLink>Log Out</LogoutLink>
                  </button>
                </>
              ) : (
                <>
                  <button className="px-3 py-1 bg-gray-800 hover:bg-blue-700 text-white rounded-md">
                    <RegisterLink>Sign Up</RegisterLink>
                  </button>
                  <button className="px-3 py-1 bg-gray-800 hover:bg-blue-700 text-white rounded-md">
                    <LoginLink>Sign In</LoginLink>
                  </button>
                </>
              )}
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
